### ISSUE TITLE
Add general playerdata files

### ISSUE THREAD

**Issue by FubyCutie** [Holes-in-the-Code/hitw-economy-plugin#2]
Add new playerdata/general/uuid.json which contains non-time-based data, like total credits, total credits earned, playtime in different gamemodes, and eventually, cosmetics

**Comment by Blackoutburst** [comment]
Related to https://github.com/Holes-in-the-Code/hitw-economy-plugin/issues/1 It's probably better to pack everything in a single file (e.g Hypixel does have every stats in a single JSON file)

**Comment by FubyCutie** [comment]
Done on branch bug/1 as it was part of data caching there.

**Comment by FubyCutie** [comment]
Done on branch feature/2.
