### ISSUE TITLE
Create util for calculating credits from scores json

### ISSUE THREAD

**Issue by FubyCutie** [Holes-in-the-Code/hitw-economy-plugin#3]
Create a method to read in a scores json for a particular player on a particular day, and calculate how many credits they should have from this, ideally make this method easily tweakable for playtesting period, then lock it in

**Comment by Blackoutburst** [comment]
So from what you said, people get credit at the end of the day based on their score of the day? They don't get credit at the end of game? Maybe it's a misunderstanding but for now that how I understand this issue and that seems a bit weird. Player should be rewarded right after a game end in my opinion

**Comment by FubyCutie** [comment]
Because one of the algorithms for credits being considered is to calculate based on the best games of that particular day, it needs to recalculate based on that day's statistics in order to find the correct amount, the credits would still be awarded after a game, but it would require the entire day's data in order to calculate the correct amount (under one of the considered algorithms)

**Comment by FubyCutie** [comment]
Done on branch [feature/3](https://github.com/Holes-in-the-Code/hitw-economy-plugin/tree/feature/3).
