### ISSUE TITLE
Create analytics utils

### ISSUE THREAD

**Issue by FubyCutie** [Holes-in-the-Code/hitw-economy-plugin#4]
These will take in the general playerdata files, and parse the data to get useful statistics, such as most played gamemodes, how many people are playing every day, whether people are maxxing out their games or not, etc

**Comment by Blackoutburst** [comment]
Maybe not reading player data unless we want to store pretty much everything. We do not have the capacity to store endless amount of data so analytics should be on a period of time like 90 days or something. In this case is probably better to have dedicated files for analytics that would:

1) Anonymise the data as this is usually how analytics works
2) Avoid unnecessary parsing as we could store only what we really need
3) Make them easier to clean after a period of time without the risk of wiping player data

**Comment by FubyCutie** [comment]
No longer necessary for this plugin
